version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rambo_db
      POSTGRES_USER: rambo_user
      POSTGRES_PASSWORD: rambo_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rambo_user -d rambo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and job queues
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend service
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://rambo_user:rambo_password@postgres:5432/rambo_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your_development_secret_here
    volumes:
      - .:/app
      - /app/node_modules

  # Optional: Prisma Studio for database exploration
  prisma-studio:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    command: npx prisma studio
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
